# Generated by Django 6.0.3 on 2026-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('entry', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('image', models.CharField(blank=True, default='https://via.placeholder.com/150', max_length=255, null=True)),
            ],
        ),
    ]
